export const ANIMATIONS = {
  CARD_SHUFFLE: require('./cardShuffle.json'),
  DANCING_MOTH: require('./dancingMoth.json'),
  FINDING_RIGHT_CHARM: require('./findingRightCharm.json'),
  GROWING_CALM_PLANT: require('./growingCalmPlant.json'),
  GROWING_COMPASSION_PLANT: require('./growingCompassionPlant.json'),
  GROWING_COURAGE_PLANT: require('./growingCouragePlant.json'),
  LEAF_CONFETTI: require('./leafConfetti.json'),
  LOADING_FOREST: require('./loadingForest.json'),
  MEDITATIVE_CALM: require('./meditativeCalm.json'),
  MEDITATIVE_COMPASSION: require('./meditativeCompassion.json'),
  POTION_MIX: require('./potionMix.json'),
  POTION_OPEN_BOTTLE: require('./potionOpenBottle.json'),
  POTION_POUR_CALM: require('./potionPourCalm.json'),
  POTION_POUR_COMPASSION: require('./potionPourCompassion.json'),
  POTION_POUR_COURAGE: require('./potionPourCourage.json'),
  TIMER: require('./timer.json'),

  TROUBLE_SOME_SPIRIT_ENDING: require('./troubleSomeSpiritEnding.json'),
  TROUBLE_SOME_SPIRIT_ENTERS: require('./troubleSomeSpiritEnters.json'),

  OPEN_HAND_STEP_FIRST: require('./openHand/openHandStepFirst.json'),
  OPEN_HAND_STEP_SECOND: require('./openHand/openHandStepSecond.json'),
  OPEN_HAND_STEP_THIRD: require('./openHand/openHandStepThird.json'),
  OPEN_HAND_STEP_FOURTH: require('./openHand/openHandStepFourth.json'),
  OPEN_HAND_STEP_FIFTH: require('./openHand/openHandStepFifth.json'),
  OPEN_HAND_STEP_SIXTH: require('./openHand/openHandStepSixth.json'),
};

export const POTION_FILL_ANIMATIONS = {
  ElixirOneHalfToElixirTwoHalf: require('./potionFill/potionFill1.5-2.5.json'),
  ElixirOneHalfToElixirTwo: require('./potionFill/potionFill1.5-2.json'),
  ElixirOneToElixirOneHalf: require('./potionFill/potionFill1-1.5.json'),
  ElixirOneToElixirTwo: require('./potionFill/potionFill1-2.json'),
  ElixirTwoHalfToElixirThree: require('./potionFill/potionFill2.5-3.json'),
  ElixirTwoToElixirThree: require('./potionFill/potionFill2-3.json'),
  ElixirTwoToElixirTwoHalf: require('./potionFill/potionFill2-2.5.json'),
  ElixirZeroHalfToElixirOne: require('./potionFill/potionFill0.5-1.json'),
  ElixirZeroHalfToElixirOneHalf: require('./potionFill/potionFill0.5-1.5.json'),
  ElixirZeroToElixirOne: require('./potionFill/potionFill0-1.json'),
  ElixirZeroToElixirThree: require('./potionFill/potionFill0-3.json'),
  ElixirZeroToElixirZeroHalf: require('./potionFill/potionFill0-0.5.json'),
};
