export const ANIMATIONS = {
  CALM_PLANT_GROWING: require('./calmPlantGrowing.json'),
  CARD_SHUFFLE: require('./cardShuffle.json'),
  COMPASSION_PLANT_GROWING: require('./compassionPlantGrowing.json'),
  COURAGE_PLANT_GROWING: require('./couragePlantGrowing.json'),
  DANCING_MOTH: require('./dancingMoth.json'),
  FINDING_RIGHT_CHARM: require('./findingRightCharm.json'),
  GROWING_CALM_PLANT: require('./growingCalmPlant.json'),
  GROWING_COMPASSION_PLANT: require('./growingCompassionPlant.json'),
  GROWING_COURAGE_PLANT: require('./growingCouragePlant.json'),
  LEAF_CONFETTI: require('./leafConfetti.json'),
  LOADING_FOREST: require('./loadingForest.json'),
  MEDITATIVE_CALM: require('./meditativeCalm.json'),
  MEDITATIVE_COMPASSION: require('./meditativeCompassion.json'),
  POTION_MIX: require('./potionMix.json'),
  POTION_OPEN_BOTTLE: require('./potionOpenBottle.json'),
  POTION_POUR_CALM: require('./potionPourCalm.json'),
  POTION_POUR_COMPASSION: require('./potionPourCompassion.json'),
  POTION_POUR_COURAGE: require('./potionPourCourage.json'),
  TIMER: require('./timer.json'),

  TROUBLE_SOME_SPIRIT_ENDING: require('./troubleSomeSpiritEnding.json'),
  TROUBLE_SOME_SPIRIT_ENTERS: require('./troubleSomeSpiritEnters.json'),

  OPEN_HAND_STEP_FIRST: require('./openHand/openHandStepFirst.json'),
  OPEN_HAND_STEP_SECOND: require('./openHand/openHandStepSecond.json'),
  OPEN_HAND_STEP_THIRD: require('./openHand/openHandStepThird.json'),
  OPEN_HAND_STEP_FOURTH: require('./openHand/openHandStepFourth.json'),
  OPEN_HAND_STEP_FIFTH: require('./openHand/openHandStepFifth.json'),
  OPEN_HAND_STEP_SIXTH: require('./openHand/openHandStepSixth.json'),
};

export const POTION_FILL_ANIMATIONS = {
  OneHalfToTwo: require('./potionFill/potionFill1.5-2.json'),
  OneHalfToTwoHalf: require('./potionFill/potionFill1.5-2.5.json'),
  OneToOneHalf: require('./potionFill/potionFill1-1.5.json'),
  OneToTwo: require('./potionFill/potionFill1-2.json'),
  TwoHalfToThree: require('./potionFill/potionFill2.5-3.json'),
  TwoToThree: require('./potionFill/potionFill2-3.json'),
  TwoToTwoHalf: require('./potionFill/potionFill2-2.5.json'),
  ZeroHalfToOne: require('./potionFill/potionFill0.5-1.json'),
  ZeroHalfToOneHalf: require('./potionFill/potionFill0.5-1.5.json'),
  ZeroToOne: require('./potionFill/potionFill0-1.json'),
  ZeroToThree: require('./potionFill/potionFill0-3.json'),
};
