export const ANIMATIONS = {
  CALM_PLANT_GROWING: require('./calmPlantGrowing.json'),
  CARD_SHUFFLE: require('./cardShuffle.json'),
  COMPASSION_PLANT_GROWING: require('./compassionPlantGrowing.json'),
  COURAGE_PLANT_GROWING: require('./couragePlantGrowing.json'),
  DANCING_MOTH: require('./dancingMoth.json'),
  FINDING_RIGHT_CHARM: require('./findingRightCharm.json'),
  LEAF_CONFETTI: require('./leafConfetti.json'),
  LOADING_FOREST: require('./loadingForest.json'),
  MEDITATIVE_CALM: require('./meditativeCalm.json'),
  MEDITATIVE_COMPASSION: require('./meditativeCompassion.json'),
  POTION_MIX: require('./potionMix.json'),
  POTION_OPEN_BOTTLE: require('./potionOpenBottle.json'),
  POTION_POUR_CALM: require('./potionPourCalm.json'),
  POTION_POUR_COMPASSION: require('./potionPourCompassion.json'),
  POTION_POUR_COURAGE: require('./potionPourCourage.json'),
  TIMER: require('./timer.json'),
};
