export const ONE_DAY_SECONDS = 60;
// export const ONE_DAY_SECONDS = 43200000;
export const TWO_DAY_SECONDS = ONE_DAY_SECONDS * 2;
export const TEN_SECONDS = 1;
export const TWENTY_SECONDS = TEN_SECONDS * 2;
export const THIRTY_SECONDS = TEN_SECONDS * 3;
export const ONE_MINUTE = 1;
export const TEN_MINUTES_SECONDS = 600;
export const SCROLL_DELAY = 100;
